// lesson-engine.js — shared rendering for all 4 hiragana lessons.
//
// Each lesson HTML calls Lesson.init({...}) with config. The engine handles:
//   - rendering the kana grid from KANA_DATA filtered to this lesson
//   - the mid-lesson mini-drill (kana → romaji input prompts)
//   - the end-of-lesson quiz (similar, with pass/fail badge)
//   - the optional reading drill (Lesson 4 only)
//   - audio playback (static MP3s in audio/<romaji>.mp3, generated by scripts/generate-audio.mjs)
//
// State is held in module-level closures. Strictly NO localStorage / sessionStorage.

(function () {
  'use strict';

  // ── Utilities ────────────────────────────────────────────────────
  function el(tag, attrs, ...children) {
    const node = document.createElement(tag);
    if (attrs) {
      for (const [k, v] of Object.entries(attrs)) {
        if (k === 'class') node.className = v;
        else if (k === 'html') node.innerHTML = v;
        else if (k.startsWith('on') && typeof v === 'function') {
          node.addEventListener(k.slice(2).toLowerCase(), v);
        } else if (v !== null && v !== undefined && v !== false) {
          node.setAttribute(k, v);
        }
      }
    }
    for (const child of children) {
      if (child === null || child === undefined || child === false) continue;
      if (typeof child === 'string' || typeof child === 'number') {
        node.appendChild(document.createTextNode(String(child)));
      } else if (Array.isArray(child)) {
        for (const c of child) node.appendChild(c);
      } else {
        node.appendChild(child);
      }
    }
    return node;
  }

  function shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }

  function normalizeAnswer(s) {
    return String(s || '').trim().toLowerCase().replace(/[\s\u3000]+/g, '');
  }

  // Romanization aliases — accept multiple romanizations.
  // Hepburn is canonical, but learners often type Nihon-shiki.
  const ROMAJI_ALIASES = {
    shi:  ['shi', 'si'],
    chi:  ['chi', 'ti'],
    tsu:  ['tsu', 'tu'],
    fu:   ['fu', 'hu'],
    ji:   ['ji', 'zi', 'di'],
    zu:   ['zu', 'du'],
    sha:  ['sha', 'sya'],
    shu:  ['shu', 'syu'],
    sho:  ['sho', 'syo'],
    cha:  ['cha', 'tya'],
    chu:  ['chu', 'tyu'],
    cho:  ['cho', 'tyo'],
    ja:   ['ja', 'jya', 'zya'],
    ju:   ['ju', 'jyu', 'zyu'],
    jo:   ['jo', 'jyo', 'zyo'],
    wo:   ['wo', 'o'],   // を is read 'o' in modern usage
    n:    ['n', 'nn'],   // ん can be typed 'n' or 'nn'
  };

  // Match either:
  //   - romaji input (e.g., "ka" → か) — standard QWERTY romaji typing
  //   - kana input  (e.g., か → か)    — JIS kana keyboard typing direct
  // The expected value in KANA_DATA is romaji, but Squibs may type the kana
  // directly in kana-input mode. Either is correct.
  function answerMatches(input, expectedRomaji, expectedKana) {
    const normalized = normalizeAnswer(input);
    if (!normalized) return false;
    // Direct kana match (kana-input typists)
    if (expectedKana && input.trim() === expectedKana) return true;
    // Romaji match with aliases (romaji-input typists)
    const aliases = ROMAJI_ALIASES[expectedRomaji] || [expectedRomaji];
    return aliases.some(a => normalizeAnswer(a) === normalized);
  }

  // ── Audio ────────────────────────────────────────────────────────
  // Static MP3s at audio/<romaji>.mp3. If the file isn't present yet
  // (Squibs hasn't run generate-audio.mjs), the button is disabled with a tooltip.
  const audioCache = {};
  function playAudio(romaji) {
    if (!audioCache[romaji]) {
      audioCache[romaji] = new Audio(`audio/${romaji}.mp3`);
      audioCache[romaji].addEventListener('error', () => {
        audioCache[romaji].dataset.failed = '1';
      });
    }
    const a = audioCache[romaji];
    a.currentTime = 0;
    const playPromise = a.play();
    if (playPromise && playPromise.catch) playPromise.catch(() => {});
  }

  // ── Renderers ────────────────────────────────────────────────────
  function renderKanaCard(entry) {
    const card = el('div', { class: 'kana-card' + (entry.irregular ? ' irregular' : '') },
      entry.irregular ? el('span', { class: 'irregular-flag' }, 'irregular') : null,
      el('div', { class: 'glyph' }, entry.kana),
      el('div', { class: 'romaji' }, entry.romaji),
      el('div', { class: 'mnemonic' }, entry.mnemonic || ''),
      el('button', {
        class: 'audio-btn',
        type: 'button',
        title: 'Click to hear pronunciation',
        onclick: (ev) => { ev.stopPropagation(); playAudio(entry.romaji); },
      }, '▶  hear it'),
    );
    // Clicking anywhere on the card (other than the audio button) highlights
    // the kana on the bottom keyboard helper. Issue #1.
    card.addEventListener('click', () => {
      if (activeKeyboardApi) activeKeyboardApi.highlightKana(entry.kana);
    });
    card.style.cursor = 'pointer';
    return card;
  }

  function renderKanaGrid(kanaList) {
    const grid = el('div', { class: 'kana-grid' });
    for (const k of kanaList) grid.appendChild(renderKanaCard(k));
    return grid;
  }

  // ── Mini-drill ───────────────────────────────────────────────────
  function buildDrill(kanaPool, count, label) {
    const wrap = el('div', { class: 'drill' });
    const header = el('h3', null, label || 'Mini-drill');
    const progress = el('div', { class: 'drill-progress' });
    const promptGlyph = el('div', { class: 'prompt-glyph' });
    const input = el('input', { type: 'text', autocomplete: 'off', placeholder: 'type romaji or kana…' });
    const feedback = el('div', { class: 'drill-feedback' });
    const playHint = el('button', { class: 'audio-btn', type: 'button' }, '▶  hear it');

    const queue = shuffle(kanaPool).slice(0, count);
    let i = 0;
    let correct = 0;

    function showCurrent() {
      if (i >= queue.length) {
        promptGlyph.textContent = '✓';
        input.style.display = 'none';
        playHint.style.display = 'none';
        progress.textContent = `Done — ${correct}/${queue.length} correct.`;
        feedback.textContent = correct === queue.length
          ? 'Clean sweep. On to the next section.'
          : 'Not bad. Re-scroll the cards above for any you missed, then carry on.';
        feedback.className = 'drill-feedback ' + (correct === queue.length ? 'correct' : '');
        return;
      }
      const current = queue[i];
      promptGlyph.textContent = current.kana;
      progress.textContent = `Drill ${i + 1} of ${queue.length}`;
      input.value = '';
      input.className = '';
      input.disabled = false;
      input.focus();
      feedback.textContent = '';
      feedback.className = 'drill-feedback';
      playHint.onclick = () => playAudio(current.romaji);
      // Highlight the kana on the bottom keyboard so Squibs can find the key
      if (activeKeyboardApi) activeKeyboardApi.highlightKana(current.kana);
    }

    input.addEventListener('keydown', (ev) => {
      if (ev.key !== 'Enter') return;
      ev.preventDefault();
      const current = queue[i];
      if (answerMatches(input.value, current.romaji, current.kana)) {
        input.classList.add('correct');
        feedback.textContent = `✓ ${current.kana} = ${current.romaji}`;
        feedback.className = 'drill-feedback correct';
        correct += 1;
        input.disabled = true;
        setTimeout(() => { i += 1; showCurrent(); }, 700);
      } else {
        input.classList.remove('correct');
        input.classList.add('wrong');
        feedback.textContent = `✗ Not quite — try again. (Hint: starts with "${current.romaji[0]}")`;
        feedback.className = 'drill-feedback wrong';
        setTimeout(() => {
          input.classList.remove('wrong');
          feedback.className = 'drill-feedback';
          input.focus();
          input.select();
        }, 900);
      }
    });

    wrap.append(header, progress, promptGlyph, playHint, input, feedback);
    showCurrent();
    return wrap;
  }

  // ── End-of-lesson quiz ───────────────────────────────────────────
  function buildQuiz(kanaPool, count, passing, opts) {
    opts = opts || {};
    const wrap = el('div', { class: 'quiz' });
    const header = el('h3', null, 'Lesson Quiz');
    const subhead = el('p', null, `${count} prompts. ${passing}/${count} to pass.`);
    const progress = el('div', { class: 'quiz-progress' });
    const promptGlyph = el('div', { class: 'prompt-glyph' });
    const input = el('input', { type: 'text', autocomplete: 'off', placeholder: 'type romaji or kana…' });
    const feedback = el('div', { class: 'quiz-feedback' });
    const result = el('div');

    const queue = shuffle(kanaPool).slice(0, count);
    let i = 0;
    let correct = 0;
    const wrong = [];

    function showCurrent() {
      if (i >= queue.length) {
        promptGlyph.textContent = correct >= passing ? '🌸' : '🌱';
        input.style.display = 'none';
        progress.textContent = '';
        feedback.textContent = '';
        const passed = correct >= passing;
        const badge = el('div', { class: 'result-badge ' + (passed ? 'passed' : 'failed') },
          passed ? `Passed — ${correct}/${queue.length}` : `${correct}/${queue.length} — try again`,
        );
        result.appendChild(badge);
        result.appendChild(el('p', null,
          passed
            ? (opts.passMsg || 'Nice. Move on when you\'re ready.')
            : 'No shame in re-reading the cards above and re-running the quiz. The kana that matter most are the ones you\'re missing.',
        ));
        if (wrong.length) {
          result.appendChild(el('p', { class: 'quiz-progress' }, 'Missed: ' + wrong.map(w => `${w.kana} (${w.romaji})`).join(', ')));
        }
        const tryAgain = el('button', { class: 'primary', type: 'button',
          onclick: () => { wrap.replaceWith(buildQuiz(kanaPool, count, passing, opts)); },
        }, 'Run the quiz again');
        result.appendChild(tryAgain);
        return;
      }
      const current = queue[i];
      promptGlyph.textContent = current.kana;
      progress.textContent = `Question ${i + 1} of ${queue.length}`;
      input.value = '';
      input.className = '';
      input.disabled = false;
      input.focus();
      feedback.textContent = '';
      feedback.className = 'quiz-feedback';
      // Quiz also highlights the keyboard — same UX as the drill
      if (activeKeyboardApi) activeKeyboardApi.highlightKana(current.kana);
    }

    input.addEventListener('keydown', (ev) => {
      if (ev.key !== 'Enter') return;
      ev.preventDefault();
      const current = queue[i];
      if (answerMatches(input.value, current.romaji, current.kana)) {
        input.classList.add('correct');
        feedback.textContent = '✓';
        feedback.className = 'quiz-feedback correct';
        correct += 1;
        input.disabled = true;
        setTimeout(() => { i += 1; showCurrent(); }, 500);
      } else {
        input.classList.add('wrong');
        feedback.textContent = `✗ — answer was "${current.romaji}"`;
        feedback.className = 'quiz-feedback wrong';
        wrong.push(current);
        input.disabled = true;
        setTimeout(() => { i += 1; showCurrent(); }, 1200);
      }
    });

    wrap.append(header, subhead, progress, promptGlyph, input, feedback, result);
    showCurrent();
    return wrap;
  }

  // ── Reading drill (Lesson 4 only) ────────────────────────────────
  function buildReadingDrill(words) {
    const wrap = el('div', { class: 'drill' });
    const header = el('h3', null, 'Reading drill');
    const intro = el('p', null,
      'Real Japanese words, written entirely in hiragana you now know. Click a card to reveal the romaji and meaning.',
    );
    const grid = el('div', { class: 'reading-grid' });
    for (const w of words) {
      const card = el('div', { class: 'reading-card' },
        el('div', { class: 'word' }, w.word),
        el('div', { class: 'reveal' }, '(click to reveal)'),
        el('div', { class: 'answer' },
          el('div', { class: 'romaji-text' }, w.romaji),
          el('div', { class: 'meaning-text' }, w.meaning),
        ),
      );
      card.addEventListener('click', () => card.classList.toggle('revealed'));
      grid.appendChild(card);
    }
    wrap.append(header, intro, grid);
    return wrap;
  }

  // ── KanaKeyboard widget (issue #1) ───────────────────────────────
  // Sticky bottom panel showing the JIS kana layout. Highlights the keys
  // for the most-recently-touched kana. Helps Squibs touch-type kana
  // input as he learns the language.
  //
  // Depends on JIS_KANA_LAYOUT and kanaToKeySequence from keyboard-data.js.
  // If the dependency isn't loaded (legacy lessons without the script tag),
  // buildKeyboard() returns null and the lesson works without the helper.

  let activeKeyboardApi = null;

  function buildKeyboard() {
    if (typeof JIS_KANA_LAYOUT === 'undefined' || typeof kanaToKeySequence !== 'function') {
      return null;  // dependency not loaded — gracefully degrade
    }

    // Default: expanded on desktop, auto-collapse on small screens via JS.
    const wrap = el('div', { class: 'kana-keyboard', id: 'kana-keyboard' });
    if (window.matchMedia && window.matchMedia('(max-width: 540px)').matches) {
      wrap.classList.add('collapsed');
    }
    const header = el('div', { class: 'kbd-header' },
      el('span', { class: 'kbd-title' }, 'JIS kana keyboard'),
      el('span', { class: 'kbd-caption', id: 'kbd-caption' }, 'click any kana above or run a drill — keys light up'),
      el('button', { class: 'kbd-toggle', type: 'button', title: 'show / hide keyboard' }, 'hide'),
    );
    const body = el('div', { class: 'kbd-body' });
    const keyEls = {};  // key string → DOM element

    for (const row of JIS_KANA_LAYOUT.rows) {
      const rowEl = el('div', { class: 'kbd-row' });
      for (const k of row) {
        const keyEl = el('button', {
          class: 'kbd-key',
          type: 'button',
          'data-key': k.key,
          title: k.shiftKana
            ? `${k.kana}  (Shift: ${k.shiftKana})`
            : (k.kana || k.label || k.key),
        },
          el('span', { class: 'kbd-key-label' }, k.key),
          el('span', { class: 'kbd-key-kana' }, k.kana || ''),
          k.shiftKana ? el('span', { class: 'kbd-key-kana-shift' }, k.shiftKana) : null,
        );
        // Clicking a key on the virtual keyboard highlights its kana — handy for
        // exploring the layout independently of the lesson cards.
        keyEl.addEventListener('click', () => {
          if (k.kana) api.highlightKana(k.kana);
        });
        keyEls[k.key] = keyEl;
        rowEl.appendChild(keyEl);
      }
      body.appendChild(rowEl);
    }

    wrap.append(header, body);

    // Toggle behavior — initial state matches the class set above
    let collapsed = wrap.classList.contains('collapsed');
    const toggleBtn = header.querySelector('.kbd-toggle');
    toggleBtn.textContent = collapsed ? 'show' : 'hide';
    toggleBtn.addEventListener('click', () => {
      collapsed = !collapsed;
      wrap.classList.toggle('collapsed', collapsed);
      toggleBtn.textContent = collapsed ? 'show' : 'hide';
    });

    const captionEl = header.querySelector('#kbd-caption');

    const api = {
      element: wrap,
      highlightKana(kana) {
        // Clear previous highlights
        for (const el of wrap.querySelectorAll('.kbd-key.active, .kbd-key.shift-active')) {
          el.classList.remove('active', 'shift-active');
          const badge = el.querySelector('.kbd-seq-badge');
          if (badge) badge.remove();
        }
        const seq = kanaToKeySequence(kana);
        if (!seq || !seq.length) {
          captionEl.textContent = `${kana} — no JIS mapping (rare combo, type via romaji)`;
          return;
        }
        // Highlight each press in the sequence with a numbered badge
        seq.forEach((press, idx) => {
          const keyEl = keyEls[press.key];
          if (!keyEl) return;
          keyEl.classList.add('active');
          if (press.shift) keyEl.classList.add('shift-active');
          if (seq.length > 1) {
            const badge = el('span', { class: 'kbd-seq-badge' }, String(idx + 1));
            keyEl.appendChild(badge);
          }
        });
        // Caption: human-readable sequence
        if (seq.length === 1) {
          captionEl.textContent = seq[0].shift
            ? `${kana} — Shift + ${seq[0].key}`
            : `${kana} — press ${seq[0].key}`;
        } else {
          const parts = seq.map((p, i) => `${i + 1}. ${p.shift ? 'Shift+' : ''}${p.key} (${p.label})`);
          captionEl.textContent = `${kana} — ${parts.join('  →  ')}`;
        }
      },
      clear() {
        for (const el of wrap.querySelectorAll('.kbd-key.active, .kbd-key.shift-active')) {
          el.classList.remove('active', 'shift-active');
          const badge = el.querySelector('.kbd-seq-badge');
          if (badge) badge.remove();
        }
        captionEl.textContent = 'click any kana above or run a drill — keys light up';
      },
    };

    return api;
  }

  // ── Public API ───────────────────────────────────────────────────
  window.Lesson = {
    /**
     * config: {
     *   number: 1..4,
     *   title: 'Vowels & K-row',
     *   intro: 'short intro paragraph',
     *   kana: KANA_DATA filtered to this lesson,
     *   miniDrill: { count: 8, label: 'Mini-drill (mix it up)' } | null,
     *   quiz: { count: 5, passing: 4, passMsg: '...' },
     *   readingDrill: READING_DRILL | null,
     *   sections: optional array of additional inline-rendered sections [{ title, html }],
     *   prevLesson: 'href' | null,
     *   nextLesson: 'href' | null,
     * }
     */
    init(config) {
      const root = document.getElementById('lesson-root');
      if (!root) {
        console.error('Lesson.init: missing #lesson-root');
        return;
      }

      // Header
      root.appendChild(el('div', { class: 'lesson-header' },
        el('div', null,
          el('div', { class: 'pack-tag' }, 'Pack 1 — Hiragana'),
          el('h1', null, `Lesson ${config.number}: ${config.title}`),
        ),
        el('a', { href: 'index.html' }, '← back to pack'),
      ));

      // Intro
      if (config.intro) {
        root.appendChild(el('p', { class: 'intro' }, config.intro));
      }

      // Kana cards
      root.appendChild(el('h2', null, 'The kana'));
      root.appendChild(renderKanaGrid(config.kana));

      // Inline sections (e.g., Lesson 2's "irregulars" callout, Lesson 3's を note)
      if (config.sections) {
        for (const s of config.sections) {
          if (s.title) root.appendChild(el('h2', null, s.title));
          if (s.html)  root.appendChild(el('div', { html: s.html }));
        }
      }

      // Mini-drill
      if (config.miniDrill) {
        root.appendChild(el('h2', null, 'Quick drill'));
        root.appendChild(buildDrill(config.miniDrillPool || config.kana, config.miniDrill.count, config.miniDrill.label));
      }

      // Reading drill (Lesson 4)
      if (config.readingDrill) {
        root.appendChild(el('h2', null, 'Read real words'));
        root.appendChild(buildReadingDrill(config.readingDrill));
      }

      // Quiz
      if (config.quiz) {
        root.appendChild(el('h2', null, 'Lesson quiz'));
        root.appendChild(buildQuiz(config.quizPool || config.kana, config.quiz.count, config.quiz.passing, config.quiz));
      }

      // Footer
      const footer = el('div', { class: 'lesson-footer' });
      footer.appendChild(config.prevLesson
        ? el('a', { href: config.prevLesson }, '← previous lesson')
        : el('span'),
      );
      footer.appendChild(el('a', { href: 'index.html' }, 'pack index'));
      footer.appendChild(config.nextLesson
        ? el('a', { href: config.nextLesson }, 'next lesson →')
        : el('span'),
      );
      root.appendChild(footer);

      // Keyboard helper (sticky bottom panel) — issue #1
      // Default-on. Can be hidden via the toggle button in its header.
      // Renders only if keyboard-data.js is loaded.
      if (config.keyboard !== false) {
        const keyboard = buildKeyboard();
        if (keyboard) {
          activeKeyboardApi = keyboard;
          document.body.appendChild(keyboard.element);
          // Add bottom padding to body so the sticky keyboard doesn't cover content
          document.body.classList.add('has-kana-keyboard');
        }
      }
    },
  };
})();
